#!/bin/bash
MESSAGE=$1
if [ -z $MESSAGE ]
  then
    MESSAGE='Undocumented'
fi
git add -A &&
git commit -m $MESSAGE &&
git pull git@github.com:orland0m/netCS.git &&
git push git@github.com:orland0m/netCS.git
